apiVersion: v1
kind: Pod
metadata:
  name: rest-api
  labels:
    name: rest-api
spec:
  containers:
  - name: rest-api
    image: thangtv611/rest-api:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
