apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: thangtv611/rest-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
